const COLORS = {
  RED: 0xf25346,
  BROWN: 0x59332e,
  PINK: 0xF5986E,
  DARK_BROWN: 0x23190f,
  LIGHT_BLUE: 0xe5f2f2,
  BLUE: 0x68c3c0,
  LIGHT_GREEN: 0x99ff99,
  GREEN: 0x33ff33,
  WHITE: 0xfffafa,
  LIGHT_YELLOW: 0xFFFCCB,
  YELLOW: 0xFFFA97,
};

const EVENTS = {
  KEY_UP: 'keyup',
  KEY_DOWN: 'keydown',
  RESIZE: 'resize',
};

const KEYS_CODES = {
  KEY_W: 'KeyW',
  KEY_A: 'KeyA',
  KEY_S: 'KeyS',
  KEY_D: 'KeyD',
  ARROW_UP: 'ArrowUp',
  ARROW_LEFT: 'ArrowLeft',
  ARROW_DOWN: 'ArrowDown',
  ARROW_RIGHT: 'ArrowRight',
  SPACE: 'Space',
};

// config
const CAMERA = {
  NEAR: 1,
  FAR: 20000,
  POSITION_X: 0,
  POSITION_Y: 0,
  POSITION_Z: 200,
  FIELD_OF_VIEW: 1000,
};

const SCENE = {
  BACKGROUND_COLOR: COLORS.WHITE,
};

const TERRAIN = {
  COLOR: COLORS.LIGHT_GREEN,
  GEOMETRY_WIDTH: 100,
  GEOMETRY_HEIGHT: 100,
  GEOMETRY_DEPTH: 100,
  ROTATE_X: 90,
  FLAT_SHADING: true,
};

const FOG = {
  FAR: CAMERA.FAR,
  COLOR: COLORS.WHITE,
  NEAR: CAMERA.FAR / 2,
};

const LIGHT = {
  FAR: CAMERA.FAR / 10,
  NEAR: CAMERA.NEAR,
  INTENSITY: 0.9,
  SKY_COLOR: COLORS.LIGHT_BLUE,
  GROUND_COLOR: COLORS.LIGHT_GREEN,
  SUN_LIGHT_COLOR: COLORS.LIGHT_YELLOW,
  SUN_DIRECTION_X: 0,
  SUN_DIRECTION_Y: 0,
  SUN_DIRECTION_Z: 0,
  SHADOW_RESOLUTION: 1024,
  SUN_VISIBILITY_DISTANCE: 500,
  AMBIENT_COLOR: COLORS.BLUE,
  AMBIENT_INTENSITY: 0.7,
};

const MOVEMENT = {
  POSITION_X: 0,
  POSITION_Y: 0,
  POSITION_Z: 0,
  ROTATION: 0,
  SPEED: 5,
};

module.exports = {
  COLORS,
  EVENTS,
  KEYS_CODES,
  CAMERA,
  SCENE,
  TERRAIN,
  FOG,
  LIGHT,
  MOVEMENT,
};
